[versions]
# Android
androidGradlePlugin = "7.4.1"
compileTargetSdk = "33"
minSdk = "23"
versionCode = "1"

lifecycle = "2.5.1"

detekt = "1.20.0"

# iOS
deploymentTarget = "14.0"

#KMM
kotlin = "1.8.0"
version = "1.0"
kotlinxCoroutines = "1.6.4"

kotlinCoroutinesTest = "1.6.4"
mockk = "1.13.2"
mockkCommon = "1.12.5"

[libraries]
#Android
viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
liveData = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }

#iOS

#KMM
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

kotlinCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutinesTest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockkCommon = { module = "io.mockk:mockk-common", version.ref = "mockkCommon" }

#JVM

[bundles]

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt" }
