# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require_relative 'env.rb'

default_platform(:android)

platform(:android) do
  desc "Release app to Github and Play Store"
  lane :release do
    test()
    generate_app(tasks: ["assembleRelease", "bundleRelease"])
    github_release(upload_assets: [lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH], lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]])
    release_to_play_store(aab: lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH])
  end
end

desc "Run all the tests"
private_lane :test do
  gradle_task(tasks: ["test"])
end

desc "Release to GitHub"
private_lane :github_release do |params|
  last_tag = last_git_tag
  tag_message = sh("git tag -l -n1 #{last_tag} | sed 's/^[^\t]*\t//'")
  set_github_release(
    repository_name: "mecoFarid/Summy",
    api_token: ENV["GTHB_PERSONAL_TOKEN"],
    name: tag_message,
    tag_name: last_tag,
    upload_assets: params[:upload_assets]
  )
end

desc "Build app"
private_lane :generate_app do |params|
  gradle_task(
    tasks: params[:tasks],
    properties: {
      "android.injected.signing.store.file" => ENV["KEYSTORE_FILE_PATH"],
      "android.injected.signing.store.password" => ENV["SIGNING_STORE_PASSWORD"],
      "android.injected.signing.key.alias" => ENV["SIGNING_KEY_ALIAS"],
      "android.injected.signing.key.password" => ENV["SIGNING_KEY_PASSWORD"]
    }
  )
end

desc "Release app to Play Store"
private_lane :release_to_play_store do |params|
  upload_to_play_store(
    track: "production",
    rollout: "1",
    aab: params[:aab],
    skip_upload_apk: true,
    skip_upload_metadata: true,
    skip_upload_changelogs: true,
    skip_upload_images: true,
    skip_upload_screenshots: true
  )
end

desc "Run tasks on directory where gradlew is located"
private_lane :gradle_task do |params|
  gradle(
    tasks: params[:tasks],
    properties: params[:properties],
    project_dir: '../'
  )
end
