# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

desc "Release app to Github and Play Store"
lane :release do
  test()
  generate_app(tasks: ["assembleRelease", "bundleRelease"])
  github_release(upload_assets: [lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]])
end

desc "Run all the tests"
private_lane :test do
  gradle_task(tasks: ["test"])
end

desc "Release to GitHub"
private_lane :github_release do |values|
  apk_output_path = ENV["APK_OUTPUT_PATH"]
  puts "REAL PATHto: #{apk_output_path}"
  sh('git fetch --tags')
  last_tag = last_git_tag
  tag_message = sh("git tag -l -n1 #{last_tag} | sed 's/^[^\t]*\t//'")
  set_github_release(
    repository_name: "mecoFarid/Summy",
    api_token: secret(key: "GITHUB_TOKEN"),
    name: tag_message,
    tag_name: last_tag,
    upload_assets: values[:upload_assets]
  )
end

desc "Build app"
private_lane :generate_app do |values|
  gradle_task(
    tasks: values[:tasks],
    properties: {
      "android.injected.signing.store.file" => secret(key: "KEYSTORE_FILE_LOCATION"),
      "android.injected.signing.store.password" => secret(key: "SIGNING_STORE_PASSWORD"),
      "android.injected.signing.key.alias" => secret(key: "SIGNING_KEY_ALIAS"),
      "android.injected.signing.key.password" => secret(key: "SIGNING_KEY_PASSWORD"),
    }
  )
end

desc "Get secret from given .properties file"
private_lane :secret do |values|
  get_properties_value(
    key: values[:key],
    path: "../automation/deployment/deployment.properties"
  )
end

desc "Run tasks on directory where gradlew is located"
private_lane :gradle_task do |values|
  gradle(
    tasks: values[:tasks],
    properties: values[:properties],
    project_dir: '../'
  )
end
