name: Build and Publish App
run-name: Build and Publish App
on:
  push:
    tags:
      - '*'

jobs:
  build:

    environment: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: fastlane release targets:github,playstore
        env:
          GTHB_PERSONAL_TOKEN: ${{ secrets.GTHB_PERSONAL_TOKEN }}
          SERVICE_ACCOUNT_KEY_CONTENT: ${{ secrets.APP_PUBLISHER_ANDROID_KEY_CONTENT_ENCODED }}
          KEYSTORE_CONTENT: ${{ secrets.KEYSTORE_CONTENT_ENCODED }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          GTHB_USERNAME: ${{ secrets.GTHB_USERNAME }}
          GTHB_PASSWORD: ${{ secrets.GTHB_PASSWORD }}
        working-directory: automation/publishing/app/google-app-store